Usage guidelines updated
cncf/cluster pull request #264
Opened 2024-04-25 10:22 UTC by idvoretskyi

CIL usage guidelines are updated to reflect the fact that we're offering the cluster services for CNCF Projects only.

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

2024-04-25 14:03 UTC, krook requested changes
Thanks Ihor. A few minor changes.

2024-04-25 14:03 UTC, krook commented on README.md
I'd drop the word "the" here

2024-04-25 14:39 UTC, krook commented on README.md
> +* Resources are provided for the [CNCF Graduated and Incubating](https://www.cncf.io/projects/), as well as the [CNCF Sanbox projects](https://www.cncf.io/sandbox-projects/).
Looks like my earlier comments here got lost... there's a typo on "sanbox"

I'd rewrite this as: 
"Priority is given first to [CNCF Graduated and Incubating](https://www.cncf.io/projects/) then [CNCF Sandbox projects](https://www.cncf.io/sandbox-projects/)."

2024-04-26 13:54 UTC, jeefy approved these changes

2024-04-26 13:55 UTC, merged